services:
  # Postgres Database for raw data
  raw:
    image: postgres:15
    container_name: raw-database
    volumes:
      - ./psql/raw/scripts:/psql/raw/scripts
      - ./psql/raw/init:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
    networks:
      - etl-project
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raw

  # PGAdmin
  dcs-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dcs-pgadmin
    restart: always
    depends_on:
      - raw
    ports:
      - 8080:80
    volumes:
      - ./psql/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: password

  spark-master:
    build: ./spark.dockerfile
    command: bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./spark:/spark
    networks:
      - etl-project
    ports:
      - 9090:8080
      - 7077:7077

  spark-worker-1:
    build: ./spark.dockerfile
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./spark:/spark
    depends_on:
      - spark-master
    networks:
      - etl-project
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077

  spark-worker-2:
    build: ./spark.dockerfile
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks:
      - etl-project
    volumes:
      - ./spark:/spark
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077

networks:
  etl-project:
    driver: bridge